name: MK Capital Partners
favicon: null
layout_spectrum: 0.8530884035862982
typography_spectrum: 0.5054921058472246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8356194538064301
  lightness: 0.37156807049177587
  saturation: 0.8726342455483973
  rhythmicContrast: 0.4820748013444245
purpose: []
